name: Update Unified EPG

on:
  schedule:
    - cron: "0 2 * * *"  # every day at 2AM UTC
  workflow_dispatch:    # allowsmanual triggerr :-)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Requests
      run: pip install requests

    - name: Run the merge script
      run: python merge_epg.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add unified_epg.xml
        git commit -m "Update unified EPG file"
        git push
