name: Update Unified EPG

permissions:
  contents: write

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: "Debug: list files"
        run: find . -type f

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run the merge script
        run: python merge_epg.py
        working-directory: ${{ github.workspace }}

      - name: Check for missing EPG entries
        run: |
          echo "Checking playlist vs unified EPG…"
          python find_missing_epg.py
        working-directory: ${{ github.workspace }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add unified_epg.xml
          git commit -m "Update unified EPG file" || echo "No changes to commit"
          git push
